TARGET			?= $(PACKAGE_NAME)
BUILD_DIR		:= $(BUILD_ROOT)/$(PACKAGE_NAME)-$(PACKAGE_VER)
STAGING_DIR		:= $(STAGING_ROOT)/usr
CMAKE_OPTIONS	:= 	-DPACKAGE_PATH=$(PACKAGE_PATH) \
					-DBUILD_DIR=$(BUILD_DIR) \
					-DPACKAGE_NAME=$(PACKAGE_NAME)